name: Alpine/i386
on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      BUILD_PATH: /tmp/build
      INSTALL_PATH: /tmp/install

    steps:

    - name: Check out source code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get swayimg version
      run: echo "VERSION=$(git describe --tags --long --always | sed 's/^v//;s/-/./')" >> $GITHUB_OUTPUT
      id: version

    - name: Build docker image
      run: docker build --tag=swayimg --file=.github/workflows/Dockerfile.Alpine .

    - name: Run docker container
      run: docker run --tty --detach --name=swayimg --volume=$PWD:$PWD:ro --workdir=$PWD swayimg

    - name: Configure
      run: >
        docker exec swayimg
        meson setup
        -D version=${{steps.version.outputs.VERSION}}
        -D compositor=enabled
        -D wayland=enabled
        -D drm=enabled
        -D man=true
        -D desktop=true
        -D bash=enabled
        -D zsh=enabled
        -D exif=enabled
        -D exr=auto
        -D gif=enabled
        -D heif=enabled
        -D jpeg=enabled
        -D jxl=enabled
        -D raw=enabled
        -D sixel=enabled
        -D svg=enabled
        -D webp=enabled
        --prefix=/usr
        --werror
        ${{ env.BUILD_PATH }}

    - name: Compile and link
      run: docker exec swayimg meson compile -C ${{ env.BUILD_PATH }}

    - name: Install
      run: >
        docker exec swayimg
        env DESTDIR=${{ env.INSTALL_PATH }}
        meson install -C ${{ env.BUILD_PATH }}

    - name: Run installed
      run: docker exec swayimg ${{ env.INSTALL_PATH }}/usr/bin/swayimg --version
